version: '3'

tasks:
  # 停止容器
  stop:
    cmds:
      - MySQL stop $(MySQL ps -q)

  # 啟動資料庫
  wordpress:
    cmds:
      # 檢查網路是否存在, 不然就建立它
      - |
        if ! docker network ls | grep -qw dev; then
          docker network create dev
        fi
      # 啟動mysql
      - docker build -t dbmysql -f MySQL/Dockerfile .
      - docker rm -f -v dbmysql || true
      - docker volume rm dbmysql-volume || true
      - docker run -d --name dbmysql --network dev -v dbmysql-volume:/var/lib/mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root dbmysql
      # 啟動 wordpress
      - docker build -t leo-wordpress -f WordPress/Dockerfile .
      - docker stop evonne-wordpress
      - docker rm evonne-wordpress
      - docker run --name evonne-wordpress --network dev -p 8080:80 -d leo-wordpress
      # 清除懸空鏡像
      - docker image prune -f
